server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /static/**


#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:9000/xxl-job-admin
#      accessToken: default_token
#    executor:
#      appname: base-frame
#      address:
#      ip: 127.0.0.1
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30

logging:
  config: classpath:log4j2-spring.xml